"""Run the integrated pipeline after scripts/export_events.py.
Risk and lifecycle cost are generated by hospital_insights.py in run_demo_pipeline.py.
"""
from run_demo_pipeline import main
if __name__ == '__main__': main()
